Acacia:
  - ACACIA_PLANKS
  - ACACIA_STAIRS

Stone:
  - SMOOTH_STONE_SLAB
  - SMOOTH_STONE
  - STONE
  - STONE_STAIRS
  - STONE_SLAB

Wool:
  - BLACK_WOOL
  - BLUE_WOOL
  - BROWN_WOOL
  - CYAN_WOOL
  - GRAY_WOOL
  - GREEN_WOOL
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_WOOL
  - LIME_WOOL
  - MAGENTA_WOOL
  - ORANGE_WOOL
  - PINK_WOOL
  - PURPLE_WOOL
  - RED_WOOL
  - WHITE_WOOL
  - YELLOW_WOOL

Cobblestone:
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE
  - MOSSY_COBBLESTONE_SLAB